@startumlheader Contact Managerfooter Authors:title Use Case Diagram'diagram directionleft to right direction'user appearanceskinparam actorStyle awesome'participantsactor "New User" as nuseractor "Existing User" as euserdatabase "Application Database" as data'use casesusecase "Sign Up" as UCausecase "Login" as UCbrectangle "Contact Manager" as contacts{    usecase "Add Contact" as UC1    usecase "Search" as UC2    usecase "Edit Contact" as UC3    usecase "Delete Contact" as UC4}'connections:User: --> nuser:User: --> eusernuser --> UCaeuser --> UCbUCa --> UC1UCa --> UC2UCa --> UC3UCa --> UC4UCb --> UC1UCb --> UC2UCb --> UC3UCb --> UC4contacts --> data@enduml